spring.application.name=openai
spring.ai.openai.api-key=need to take from my personal computer
logging.level.org.springframework.ai.chat.client.advisor=DEBUG

spring.datasource.url=jdbc:h2:file:C:\\Users\\003UUD744\\Desktop\\chatmemory;AUTO_SERVER=true
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sampa
spring.datasource.password=12345

spring.ai.chat.memory.repository.jdbc.initialize-schema=always
spring.ai.chat.memory.repository.jdbc.schema=classpath:/schema/schema-h2db.sql

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
